print ("Space:")
print ("A really big place")
print ("that contains a lot of stuff")
print ("and a lot of nothing between the stuff.")
print ("This is why it is called space.")
print ("")
print ("This definition of space is stupid.")
print ("")
print ("")
print ("Chandana:")
print ("C harming")
print ("H appy")
print ("A pple")
print ("N oisy")
print ("D edicated")
print ("A corn")
print ("N eck Urself")
print ("A wesome")
